/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCbSplatRouteImport } from './routes/api/cb/$'
import { Route as ApiFngSplatRouteImport } from './routes/api/fng/$'
import { Route as ApiPaprikaSplatRouteImport } from './routes/api/paprika/$'
import { Route as ApiPumpSplatRouteImport } from './routes/api/pump/$'
import { Route as ApiS1SplatRouteImport } from './routes/api/s1/$'
import { Route as ApiXauSplatRouteImport } from './routes/api/xau/$'
import { Route as ApiYfSplatRouteImport } from './routes/api/yf/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCbSplatRoute = ApiCbSplatRouteImport.update({
  id: '/api/cb/$',
  path: '/api/cb/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFngSplatRoute = ApiFngSplatRouteImport.update({
  id: '/api/fng/$',
  path: '/api/fng/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaprikaSplatRoute = ApiPaprikaSplatRouteImport.update({
  id: '/api/paprika/$',
  path: '/api/paprika/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPumpSplatRoute = ApiPumpSplatRouteImport.update({
  id: '/api/pump/$',
  path: '/api/pump/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS1SplatRoute = ApiS1SplatRouteImport.update({
  id: '/api/s1/$',
  path: '/api/s1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXauSplatRoute = ApiXauSplatRouteImport.update({
  id: '/api/xau/$',
  path: '/api/xau/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYfSplatRoute = ApiYfSplatRouteImport.update({
  id: '/api/yf/$',
  path: '/api/yf/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cb/$': typeof ApiCbSplatRoute
  '/api/fng/$': typeof ApiFngSplatRoute
  '/api/paprika/$': typeof ApiPaprikaSplatRoute
  '/api/pump/$': typeof ApiPumpSplatRoute
  '/api/s1/$': typeof ApiS1SplatRoute
  '/api/xau/$': typeof ApiXauSplatRoute
  '/api/yf/$': typeof ApiYfSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cb/$': typeof ApiCbSplatRoute
  '/api/fng/$': typeof ApiFngSplatRoute
  '/api/paprika/$': typeof ApiPaprikaSplatRoute
  '/api/pump/$': typeof ApiPumpSplatRoute
  '/api/s1/$': typeof ApiS1SplatRoute
  '/api/xau/$': typeof ApiXauSplatRoute
  '/api/yf/$': typeof ApiYfSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cb/$': typeof ApiCbSplatRoute
  '/api/fng/$': typeof ApiFngSplatRoute
  '/api/paprika/$': typeof ApiPaprikaSplatRoute
  '/api/pump/$': typeof ApiPumpSplatRoute
  '/api/s1/$': typeof ApiS1SplatRoute
  '/api/xau/$': typeof ApiXauSplatRoute
  '/api/yf/$': typeof ApiYfSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cb/$'
    | '/api/fng/$'
    | '/api/paprika/$'
    | '/api/pump/$'
    | '/api/s1/$'
    | '/api/xau/$'
    | '/api/yf/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cb/$'
    | '/api/fng/$'
    | '/api/paprika/$'
    | '/api/pump/$'
    | '/api/s1/$'
    | '/api/xau/$'
    | '/api/yf/$'
  id:
    | '__root__'
    | '/'
    | '/api/cb/$'
    | '/api/fng/$'
    | '/api/paprika/$'
    | '/api/pump/$'
    | '/api/s1/$'
    | '/api/xau/$'
    | '/api/yf/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCbSplatRoute: typeof ApiCbSplatRoute
  ApiFngSplatRoute: typeof ApiFngSplatRoute
  ApiPaprikaSplatRoute: typeof ApiPaprikaSplatRoute
  ApiPumpSplatRoute: typeof ApiPumpSplatRoute
  ApiS1SplatRoute: typeof ApiS1SplatRoute
  ApiXauSplatRoute: typeof ApiXauSplatRoute
  ApiYfSplatRoute: typeof ApiYfSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cb/$': {
      id: '/api/cb/$'
      path: '/api/cb/$'
      fullPath: '/api/cb/$'
      preLoaderRoute: typeof ApiCbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fng/$': {
      id: '/api/fng/$'
      path: '/api/fng/$'
      fullPath: '/api/fng/$'
      preLoaderRoute: typeof ApiFngSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paprika/$': {
      id: '/api/paprika/$'
      path: '/api/paprika/$'
      fullPath: '/api/paprika/$'
      preLoaderRoute: typeof ApiPaprikaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pump/$': {
      id: '/api/pump/$'
      path: '/api/pump/$'
      fullPath: '/api/pump/$'
      preLoaderRoute: typeof ApiPumpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s1/$': {
      id: '/api/s1/$'
      path: '/api/s1/$'
      fullPath: '/api/s1/$'
      preLoaderRoute: typeof ApiS1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xau/$': {
      id: '/api/xau/$'
      path: '/api/xau/$'
      fullPath: '/api/xau/$'
      preLoaderRoute: typeof ApiXauSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yf/$': {
      id: '/api/yf/$'
      path: '/api/yf/$'
      fullPath: '/api/yf/$'
      preLoaderRoute: typeof ApiYfSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCbSplatRoute: ApiCbSplatRoute,
  ApiFngSplatRoute: ApiFngSplatRoute,
  ApiPaprikaSplatRoute: ApiPaprikaSplatRoute,
  ApiPumpSplatRoute: ApiPumpSplatRoute,
  ApiS1SplatRoute: ApiS1SplatRoute,
  ApiXauSplatRoute: ApiXauSplatRoute,
  ApiYfSplatRoute: ApiYfSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
